### ISSUE TITLE
bug: Hide game section in video description doesn't work.

### ISSUE THREAD

**Issue by Pikasatupu75** [anddea/revanced-patches#332]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube 19.05.36
ReVanced Patches 2.224.0-dev.8
ReVanced Integrations 0.151.0-dev.7

### Bug description

Turning on 'Hide game sections' setting under description in general settings doesn't work. Instead 'Hide music sections' setting hides both game sections and music sections.
![Screenshot_20240417-233411_ReVanced Extended](https://github.com/anddea/revanced-patches/assets/126986435/c33296e8-ab69-44ce-8500-b8280c183f7b)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Francesco146** [comment]
should be addressed here: [74c0022](https://github.com/anddea/revanced-integrations/commit/74c0022865353e750cfff807185086ada311119f), repatch using the latest dev-release of integrations

**Comment by anddea** [comment]
Yes. It is fixed though there is a little compromise that maybe I'll fix later.

**Comment by Pikasatupu75** [comment]
I just updated to v19.14.43 but I still have this bug. Is it not fixed?

**Comment by Francesco146** [comment]
> I just updated to v19.14.43 but I still have this bug. Is it not fixed?

after this update i can confirm it's reproducible. consider reopening this :)

I'll provide this link for reference:
[youtu.be/R18dA_ej3Gc](https://youtu.be/R18dA_ej3Gc)

**Comment by Pikasatupu75** [comment]
It might be the compromise. I noticed it is a little different. I can hide the music but not games. Before, it was only both games and music hidden together.

**Comment by anddea** [comment]
I just opened provided link and it hides Games section for me. Although, if you turn on the option you have to reopen video (close and open player, change video) or restart the app. If you still face the issue, then probably there's something new again, you have to provide logs for that section to check buffer.

**Comment by Pikasatupu75** [comment]
How can I provide the logs for you?

**Comment by Francesco146** [comment]
> How can I provide the logs for you?

it's quite time consuming, you'll need to re-patch YouTube enabling the `Enable debug logging` patch, then use Termux and run the command `logcat`. You might need root or have to use adb (simply connect to a pc with adb installed and enable usb debug, there's plenty of guides online). you can also use any application from the Play Store to display logcat logs as well

**Comment by anddea** [comment]
You can upload here, all we need is just small portion for games section (filter out by game title for example).

**Comment by Pikasatupu75** [comment]
Personally, I feel like moving it to Bottom player makes more sense. But I am fine with anything.

**Comment by Francesco146** [comment]
> Should I move this section to Player settings? I think it's a better place for description elements.

in my opinion, either Bottom player section or create a different section for these settings could work. now that there is the opportunity, in my opinion the "General" section is too mixed with settings. a search bar in the ReVanced Extended setting could be extremely useful, It would also help to create new settings sections to make them more tidy

**Comment by Francesco146** [comment]
@anddea there you go, hopefully you find it useful :)
[(game issue)description-filtered-by-title.log](https://github.com/anddea/revanced-patches/files/15082351/game.issue.description-filtered-by-title.log)

**Comment by anddea** [comment]
Can you grab everything with "video_attributes_section" string?

**Comment by Francesco146** [comment]
> Can you grab everything with "video_attributes_section" string?


sure.

[video_attributes_section.log](https://github.com/anddea/revanced-patches/files/15099538/video_attributes_section.log)

**Comment by anddea** [comment]
There's no buffer though. Previously `video_attributes_section` was the reason that both Games and Music sections were hidden (which is mentioned in description of this issue), so we need buffer content to filter based on contents of the section. 

Do you want to try to fix this? It should be easier than hiding Shorts comment button based on its state.

**Comment by Francesco146** [comment]
> There's no buffer though. 

i just noticed, that's odd. i enabled it. Although i'm grepping for logs that contains `video_attributes_section` string in them. I'll upload the result of this:
```bash
adb logcat | grep -wE "video_attributes_section|Dying Light"
```

[video_attributes_sectionORgametitle.log](https://github.com/anddea/revanced-patches/files/15107042/video_attributes_sectionORgametitle.log)


> Previously `video_attributes_section` was the reason that both Games and Music sections were hidden (which is mentioned in description of this issue), so we need buffer content to filter based on contents of the section.

thanks for the info!

> Do you want to try to fix this? It should be easier than hiding Shorts comment button based on its state.

i'm really finding difficult understanding ReVanced's codebase. I just don't know where to look! I'll try setting up your dev environment right now, however i tried this custom filter that hides the game section in the description; not sure if there's other consequences tho.

`ContainerType|CollectionType|CellType|video_attribute.eml|`

**Comment by anddea** [comment]
It works with both of CLI versions. If `video_attribute.eml` doesn't hide Music but hides Games, we can use it, but I think it should hide both of them.

**Comment by Francesco146** [comment]
> It works with both of CLI versions. 

i've set up all the things needed!

> If `video_attribute.eml` doesn't hide Music but hides Games, we can use it

sadly, it hides the cover of the song.

**Comment by anddea** [comment]
Maybe it's better to join this options and hide both of them. Because I couldn't see anything in logs that can be grabbed for Games but not for Music. 

And as for me my fix works, it hides game section for me and music as well, both are separated but it doesntwork for you and I see no related string in your logs too.

**Comment by anddea** [comment]
Sure

**Comment by Francesco146** [comment]
sadly, i was not able to keep the Music section while hiding the Games' one. joining these settings might be our only options.

**Comment by anddea** [comment]
I have "GamC" for every game section, but you don't for some reason. It looks like there is nothing in the buffer for you. Can you recheck again different game titles (i.e. different videos with different games) if they have anything similar in their buffer.  You can use logcat app from Play Store, it has good filtering options.

**Comment by Francesco146** [comment]
sure, do you want share the video links that you tested? so we are aligned with the different logs

**Comment by anddea** [comment]
It doesn't really matter, I just searched for different game walkthroughs or game trailers and for me game section is hidden in all videos from any channel.

**Comment by Francesco146** [comment]
here's the new logs:

[NEW_LOGS_GAMES.log](https://github.com/anddea/revanced-patches/files/15171250/NEW_LOGS_GAMES.log)

and some infos:
1. YouTube: `v19.16.38`
2. Video tested: [youtu.be/sgHDIUxR23E](https://youtu.be/sgHDIUxR23E)
3. Patches version: `2.225.0-dev.1`
4. Integrations version: `0-152-0-dev.1`
